version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - ./tmp/mysql/data:/var/lib/mysql
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
      - "bundle:/app/vendor/bundle"
      - "log:/app/log"
    ports:
      - "3000:3000"
    environment:
      JUUCY_DATABASE_USER: "root"
      JUUCY_DATABASE_PASSWORD: "password"
      JUUCY_DATABASE_HOST: mysql
      PORT: 3000
    depends_on:
      - mysql
  sidekiq:
    build: .
    command: "bundle exec sidekiq -C config/sidekiq.yml"
    volumes:
      - .:/app
      - "bundle:/app/vendor/bundle"
      - "log:/app/log"
    environment:
      JUUCY_DATABASE_USER: "root"
      JUUCY_DATABASE_PASSWORD: "password"
      JUUCY_DATABASE_HOST: mysql
    depends_on:
      - mysql
volumes:
  bundle:
    driver: local
  log:
    driver: local