apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: juucy
spec:
  replicas: 2
#  selector:
#    matchLabels:
#      app: juucy
  template:
    metadata:
      labels:
        app: juucy
    spec:
      containers:
        - name: juucy
          image: gcr.io/saki-185412/juucy:v0.3
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: cloud-db-credentials
                  key: host
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: cloud-db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cloud-db-credentials
                  key: password
          ports:
            - containerPort: 3000
