apiVersion: v1
kind: Service
metadata:
  name: juucy-lb
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: juucy
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: juucy-svc
#spec:
#  type: NodePort
#  selector:
#    app: juucy
#  ports:
#    - port: 3000
#      targetPort: 3000
#      protocol: TCP
